[package]
name = "modern-typst-resume"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Peter Egger <@peterpf>"]
license = "MIT"
description = "A modern resume template."
keywords = ["resume", "colorful"]
categories = ["cv"]
compiler = "0.10.0"
exclude = []

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
